### ISSUE TITLE
ERROR: Playlist Player: skipping unplayable item

### ISSUE THREAD

**Issue by BlairServices** [eracknaphobia/plugin.video.mlbtv#21]
All seemed to work well on opening day, but since then live streams have not played. Can see "Today's Games >> able to pick a game >> able to select Home or Away feed" then raises error.
=================================================
22:08:04.004 T:1134556064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'ICON' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mlbtv/main.py", line 42, in <module>
                                                stream_select(game_pk)
                                              File "/storage/.kodi/addons/plugin.video.mlbtv/resources/lib/mlb.py", line 225, in stream_select
                                                stream_url, headers = account.get_stream(media_id[n-1])
                                              File "/storage/.kodi/addons/plugin.video.mlbtv/resources/lib/account.py", line 190, in get_stream
                                                dialog.notification(title, msg, ICON, 5000, False)
                                            NameError: global name 'ICON' is not defined
                                            -->End of Python script error report<--
22:08:04.277 T:1945274832   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mlbtv/?mode=104&name=%5BB%5D%5BCOLOR%3DFFF69E20%5DB+6th%5B%2FCOLOR%5D+%5BCOLOR%3DFFAB0003%5DNationals%5B%2FCOLOR%5D+%5BCOLOR%3DFF00B7EB%5D5%5B%2FCOLOR%5D+at+Braves+%5BCOLOR%3DFF00B7EB%5D11%5B%2FCOLOR%5D%5B%2FB%5D&game_pk=529483&stream_date=2018-04-03]
=================================================

**Comment by BlairServices** [comment]
[01_KODI.log](https://github.com/eracknaphobia/plugin.video.mlbtv/files/1876501/01_KODI.log)

**Comment by eracknaphobia** [comment]
I can fix this error, but you will still have issues as this line is trying to pop a message as to why the stream can't start. Try disabling and vpn or proxies you are using and test again.

**Comment by BlairServices** [comment]
OK thanks. Will try later today.

**Comment by BlairServices** [comment]
Latest log file. It appears to work with the VPN disabled. 
[01_KODI.log](https://github.com/eracknaphobia/plugin.video.mlbtv/files/1883596/01_KODI.log)

**Comment by powsniffer0110** [comment]
I am having the same exact issue, can select today's games, see the list of games, select home or Away, then the item fails to play. I do not have any VPN or proxy set up at all either. I have not been able to get this working at All since the season started. Please help. I have correct login And most current update version.

**Comment by powsniffer0110** [comment]
Nevermind previous comment, I updated to latest version from a couple days ago and checked and unchecked the proxy option And it seems to be working. Thanks for all the hard work
