### ISSUE TITLE
Error when trying to watch the All Star Game

### ISSUE THREAD

**Issue by bontibon** [eracknaphobia/plugin.video.mlbtv#6]
When selecting Today's Games (2016-07-12), the menu fails to load. The following error message is shown in the error log:

```
23:57:07 T:2821708608  NOTICE: -->Python Interpreter Initialized<--
23:57:07 T:2821708608  NOTICE: Mode: 100
23:57:07 T:2821708608  NOTICE: Name: Today's Games
23:57:08 T:2821708608  NOTICE: GAME DAY = 2016-07-12
23:57:08 T:2821708608  NOTICE: URL GAME DAY
23:57:08 T:2821708608  NOTICE: http://gdx.mlb.com/components/game/mlb/year_2016/month_07/day_12/grid_ce.json
23:57:08 T:2821708608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mlbtv/main.py", line 982, in <module>
                                                todaysGames(None)
                                              File "/storage/.kodi/addons/plugin.video.mlbtv/main.py", line 55, in todaysGames
                                                createGameListItem(game, game_day)
                                              File "/storage/.kodi/addons/plugin.video.mlbtv/main.py", line 64, in createGameListItem
                                                icon = getGameIcon(game['home_team_id'],game['away_team_id'])
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--
23:57:08 T:3046144384   ERROR: GetDirectory - Error getting plugin://plugin.video.mlbtv/?icon=%2fstorage%2f.kodi%2faddons%2fplugin.video.mlbtv%2ficon.png&mode=100&nam
e=Today%27s%20Games
23:57:08 T:3046144384   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mlbtv/?icon=%2fstorage%2f.kodi%2faddons%2fplugin.video.mlbtv%2ficon.png&mode=100&na
me=Today%27s%20Games) failed
23:57:08 T:2821708608  NOTICE: Thread LanguageInvoker start, auto delete: false
```

I am able to watch from my browser by selecting "International MLB.TV Subscribers - Watch Now"

**Comment by bontibon** [comment]
I fixed it. I'll submit a PR shortly.
